
services:
  ui-search-app:
    build:
      context: .
      dockerfile: .
    container_name: ui-search-app-container
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
    depends_on:
      - search-service
    networks:
      - state-less-network

networks:
  state-less-network:
    driver: bridge