
services:
  ui-search-app:
    build:
      context: .
      dockerfile: Dockerfile-development
    container_name: ui-search-app-container
    environment:
      - NODE_ENV=development
    ports:
      - "3000:80"
    networks:
      - state-less-network

networks:
  state-less-network:
    driver: bridge